name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: Debian 12 Release Bookworm

    strategy:
      matrix:
        node-version: [18.xLTS]

    steps:
    - uses: actions/checkout@v3

    - name: Node.js v18.16.1
      uses: actions/setup-node.js@v18
      with:
        node-version: $ Node.js v18.16.1 

    - name: Build
      run: |
        npm install
        npx webpack
